# Generated by Django 2.2.6 on 2019-10-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Content.Content')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
            bases=('Content.content',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Content.Content')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
            ],
            bases=('Content.content',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Content.Content')),
                ('description', models.CharField(max_length=50)),
            ],
            bases=('Content.content',),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Content.Media')),
                ('the_image', models.ImageField(upload_to='')),
            ],
            bases=('Content.media',),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Content.Content')),
                ('title', models.CharField(max_length=50)),
                ('questions', models.ManyToManyField(to='Content.Question')),
            ],
            bases=('Content.content',),
        ),
    ]
