# Generated by Django 2.2.6 on 2019-10-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_content_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(default='U', editable=False, max_length=1),
            preserve_default=False,
        ),
    ]
