# Generated by Django 2.2.6 on 2019-10-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0004_content_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content_type',
        ),
    ]
