# Generated by Django 2.2.6 on 2019-10-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0005_remove_content_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='Content.Subject'),
        ),
    ]
