# Generated by Django 2.2.6 on 2019-10-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0006_auto_20191026_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='test',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
