# Generated by Django 2.2.6 on 2019-10-26 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0007_content_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='test',
        ),
    ]
