# Generated by Django 2.2.6 on 2019-10-27 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0009_article_title_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title_picture',
        ),
    ]
