# Generated by Django 2.2.6 on 2019-10-27 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0010_remove_article_title_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
