# Generated by Django 2.2.6 on 2019-10-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0012_auto_20191027_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title_picture',
            field=models.ImageField(blank=True, upload_to='static/pictures/'),
        ),
    ]
