# Generated by Django 2.2.6 on 2019-10-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Content', '0002_article_event_image_media_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('favourites', models.ManyToManyField(to='Content.Content')),
            ],
        ),
    ]
